repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.9
    hooks:
      - id: uv-lock
      - id: uv-export
        name: uv-export
        args: ["--no-hashes", "--dev", "-o", "requirements.txt"]
